package com.JCC.LeAtcoderAPI.services;

import com.JCC.LeAtcoderAPI.Model.User.User;
import com.JCC.LeAtcoderAPI.repositories.UserRepository;
import org.bson.types.ObjectId;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.NoSuchElementException;
import java.util.Optional;

@Service
public class UserService {
    private final UserRepository userRepository;
    UserService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    public User getAllUserInfo(String userId) {
        ObjectId objectId = new ObjectId(userId);
        Optional<User> user = userRepository.findById(objectId);
        return user.orElse(null);
    }

    public User findOrCreateByGoogleId(String googleId) {
        Optional<User> user = userRepository.findByGoogleId(googleId);
        return user.orElseGet(() -> new User(
                null, // provided and generated by mongo
                googleId,
                "",
                0,
                0,
                0,
                new ArrayList<>(),
                new ArrayList<>()
        ));
    }

    private ObjectId getObjectIdAndCheckInDb(String _id) {
        ObjectId objectId = new ObjectId(_id);
        Optional<User> user = userRepository.findById(objectId);
        if (user.isEmpty()) {
            throw new NoSuchElementException("User with _id " + _id + " not found.");
        }
        return objectId;
    }

    public void editUserName(String _id, String userName) {
        ObjectId objectId = this.getObjectIdAndCheckInDb(_id);
        this.userRepository.editUserName(objectId, userName);
    }

    public void updateUserRank(String _id, int rank) {
        ObjectId objectId = this.getObjectIdAndCheckInDb(_id);
        this.userRepository.updateUserRank(objectId, rank);
    }

    public void updateUserPercentile(String _id, double percentile) {
        ObjectId objectId = this.getObjectIdAndCheckInDb(_id);
        this.userRepository.updateUserPercentile(objectId, percentile);
    }

    public void updateUserRating(String _id, int rating) {
        ObjectId objectId = this.getObjectIdAndCheckInDb(_id);
        this.userRepository.updateUserRating(objectId, rating);
    }
}
